DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users () VALUES ();

DROP TABLE IF EXISTS properties CASCADE;
CREATE TABLE properties () VALUES ();

DROP TABLE IF EXISTS reservations CASCADE;
CREATE TABLE reservations () VALUES ();

DROP TABLE IF EXISTS property_reviews CASCADE;
CREATE TABLE property_reviews () VALUES ();